// Generated by CoffeeScript 1.8.0
(function() {
  var ArtCarouselController, app,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  app = angular.module('gallery');

  ArtCarouselController = (function(_super) {
    __extends(ArtCarouselController, _super);

    function ArtCarouselController() {
      return ArtCarouselController.__super__.constructor.apply(this, arguments);
    }

    ArtCarouselController.register(app, "ArtCarouselController");

    ArtCarouselController.inject('$scope');

    ArtCarouselController.prototype.initialize = function() {
      this.$scope.slides = [];
      this.$scope.slides.push({
        text: 'text1',
        image: 'http://www.whyi.net/hyunju/app/webroot/img/slide-1.jpg'
      });
      this.$scope.slides.push({
        text: 'text2',
        image: 'http://www.whyi.net/hyunju/app/webroot/img/slide-2.jpg'
      });
      this.$scope.slides.push({
        text: 'text3',
        image: 'http://www.whyi.net/hyunju/app/webroot/img/slide-3.jpg'
      });
      this.$scope.slides.push({
        text: 'text4',
        image: 'http://www.whyi.net/hyunju/app/webroot/img/slide-4.jpg'
      });
      this.$scope.slides.push({
        text: 'text5',
        image: 'http://www.whyi.net/hyunju/app/webroot/img/slide-5.jpg'
      });
      return this.$scope.myInterval = 5000;
    };

    return ArtCarouselController;

  })(BaseController);

}).call(this);
