// Generated by CoffeeScript 1.8.0
(function() {
  var MenuController, app,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  app = angular.module('gallery');

  MenuController = (function(_super) {
    var ARTS_PATH, DEFAULT_ERROR_MESSAGE;

    __extends(MenuController, _super);

    function MenuController() {
      return MenuController.__super__.constructor.apply(this, arguments);
    }

    MenuController.register(app, "MenuController");

    MenuController.inject('$scope', '$http', '$window', '$state');

    ARTS_PATH = app.sitePrefix + "/arts.json";

    DEFAULT_ERROR_MESSAGE = "Sorry, there was an error.";

    MenuController.prototype.initialize = function() {
      this.$scope.arts = {};
      this.$scope.prefix = app.sitePrefix;
      return this.loadArts();
    };

    MenuController.prototype.reportError = function(errorMessage) {
      if (errorMessage == null) {
        errorMessage = DEFAULT_ERROR_MESSAGE;
      }
      return this.$scope.errorMessage = errorMessage;
    };

    MenuController.prototype.loadArts = function() {
      console.log("loadArts ");
      return this.$http.get(ARTS_PATH).success((function(_this) {
        return function(response) {
          console.log("got " + response);
          return _this.$scope.arts = response;
        };
      })(this)).error((function(_this) {
        return function(response) {
          return _this.reportError(response["errorMessage"]);
        };
      })(this));
    };

    return MenuController;

  })(BaseController);

}).call(this);
